version: "3"

networks:
  monitoring_stack_loki:
    external: true
  mongodb_dbs:
    external: true

services:

 fin_metrics:
   container_name: fin_metrics
   restart: always
   build: ./
   ports:
     - "8001:8001"
   networks:
     - monitoring_stack_loki
     - mongodb_dbs
